apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: iauf54hvu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iauf54hvu-python 
  name: iauf54hvu-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: iauf54hvu-python
    weight: 100 
