apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iauf54hvu-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iauf54hvu-python 
  name: iauf54hvu-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iauf54hvu-python 
